11 car module file implemetation
Iron-Hills-Dev/flask-teaser pull request #17
Opened 2022-05-05 10:18 UTC by GALJO

Added port for saving cars in file system

2022-05-05 12:43 UTC, gerardolenski requested changes

2022-05-05 12:43 UTC, gerardolenski commented on domain/car/adapter/dummy/dummy_car_modify_port.py
> +        return True
Czemu tak?

2022-05-05 12:43 UTC, gerardolenski commented on domain/car/adapter/file/file_car_modify_port.py
> +class FileCarModifyPort(CarModifyPort):
Ach. Tu zrobiliśmy błąd. Implementacja portu to jest `Adapter` Czyli klasa powinna się nazywać`FileCarModifyAdapter`. Tak samo pozostałe implementacje. Trzeba to zmienić.

2022-05-05 12:43 UTC, gerardolenski commented on domain/car/adapter/file/file_car_modify_port.py
> +    def delete_car(self, _car_id: UUID) -> bool:
Po co ten `boolean` w wyniku. Ta metoda nic nie powinna zwracać.

2022-05-05 12:43 UTC, gerardolenski commented on README.md
> +**FILE** - saves cars in data folder chosen with TEASER_CAR_DATA_DIR (path to folder):\
Ładny opis :+1:

2022-05-05 12:43 UTC, gerardolenski commented on infrastructure/car_file_module/create_data_structure.py
> +import logging
dziwna nazwa dla tego pliku. Powinien być rzeczownik. folder też się dziwnie nazywa. Może `data/car_module_structure.py` ?

2022-05-05 12:43 UTC, gerardolenski commented on infrastructure/car_file_module/create_data_structure.py
> +def init_data_structure(_path: str):
Rozumiemn że to jest główna funkcja w tym pliku? To na górę ją przesuń pls.

2022-05-09 10:00 UTC, GALJO commented on domain/car/adapter/dummy/dummy_car_modify_port.py
> +        return True
No `pass` się raczej używa w przypadku tworzenia pustych struktur funkcji jako wypełniacz

2022-05-17 18:04 UTC, gerardolenski approved these changes

2022-05-20 15:02 UTC, merged